wger/core/urls.py
# -*- coding: utf-8 -*-

# This file is part of wger Workout Manager.
#
# wger Workout Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# wger Workout Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License


# Django
from django.conf.urls import (
    include,
    url
)
from django.contrib.auth import views
from django.urls import path
from django.views.generic import TemplateView

# wger
from wger.core.forms import UserLoginForm
from wger.core.views import (
    languages,
    license,
    misc,
    repetition_units,
    user,
    weight_units
)


# sub patterns for languages
patterns_language = [
    path('list',
         languages.LanguageListView.as_view(),
         name='overview'),
    path('<int:pk>/view',
         languages.LanguageDetailView.as_view(),
         name='view'),
    path('<int:pk>/delete',
         languages.LanguageDeleteView.as_view(),
         name='delete'),
    path('<int:pk>/edit',
         languages.LanguageEditView.as_view(),
         name='edit'),
    path('add',
         languages.LanguageCreateView.as_view(),
         name='add'),
]

# sub patterns for user
patterns_user = [
    path('login',
         views.LoginView.as_view(template_name='user/login.html',
                                 authentication_form=UserLoginForm),
         name='login'),
    path('logout',
         user.logout,
         name='logout'),
    path('delete',
         user.delete,
         name='delete'),
    path('<int:user_pk>/delete',
         user.delete,
         name='delete'),
    path('<int:user_pk>/trainer-login',
         user.trainer_login,
         name='trainer-login'),
    path('registration',
         user.registration,
         name='registration'),
    path('preferences',
         user.preferences,
         name='preferences'),
    path('api-key',
         user.api_key,
         name='api-key'),
    path('demo-entries',
         misc.demo_entries,
         name='demo-entries'),
    path('<int:pk>/activate',
         user.UserActivateView.as_view(),
         name='activate'),
    path('<int:pk>/deactivate',
         user.UserDeactivateView.as_view(),
         name='deactivate'),
    path('<int:pk>/edit',
         user.UserEditView.as_view(),
         name='edit'),
    path('<int:pk>/overview',
         user.UserDetailView.as_view(),
         name='overview'),
    path('list',
         user.UserListView.as_view(),
         name='list'),

    # Password reset is implemented by Django, no need to cook our own soup here
    # (besides the templates)
    path('password/change',
         user.WgerPasswordChangeView.as_view(),
         name='change-password'),
    path('password/reset/',
         user.WgerPasswordResetView.as_view(),
         name='password_reset'),
    path('password/reset/done/',
         views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    url(r'^password/reset/check/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,33})$',
        user.WgerPasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('password/reset/complete/',
         views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]


# sub patterns for licenses
patterns_license = [
    path('license/list',
         license.LicenseListView.as_view(),
         name='list'),
    path('license/add',
         license.LicenseAddView.as_view(),
         name='add'),
    path('license/<int:pk>/edit',
         license.LicenseUpdateView.as_view(),
         name='edit'),
    path('license/<int:pk>/delete',
         license.LicenseDeleteView.as_view(),
         name='delete'),
]

# sub patterns for setting units
patterns_repetition_units = [
    path('list',
         repetition_units.ListView.as_view(),
         name='list'),
    path('add',
         repetition_units.AddView.as_view(),
         name='add'),
    path('<int:pk>/edit',
         repetition_units.UpdateView.as_view(),
         name='edit'),
    path('<int:pk>/delete',
         repetition_units.DeleteView.as_view(),
         name='delete'),
]

# sub patterns for setting units
patterns_weight_units = [
    path('list',
         weight_units.ListView.as_view(),
         name='list'),
    path('add',
         weight_units.AddView.as_view(),
         name='add'),
    path('<int:pk>)/edit',
         weight_units.UpdateView.as_view(),
         name='edit'),
    path('<int:pk>/delete',
         weight_units.DeleteView.as_view(),
         name='delete'),
]


#
# Actual patterns
#
urlpatterns = [

    # The landing page
    path('',
         misc.index,
         name='index'),

    # The dashboard
    path('dashboard',
         misc.dashboard,
         name='dashboard'),

    # Others
    path('about',
         TemplateView.as_view(template_name="misc/about.html"),
         name='about'),
    path('contact',
         misc.ContactClassView.as_view(template_name="misc/contact.html"),
         name='contact'),
    path('feedback',
         misc.FeedbackClass.as_view(),
         name='feedback'),

    path('language/', include((patterns_language, 'language'), namespace="language")),
    path('user/', include((patterns_user, 'user'), namespace="user")),
    path('license/', include((patterns_license, 'license'), namespace="license")),
    path('repetition-unit/', include((patterns_repetition_units, 'repetition-unit'), namespace="repetition-unit")),
    path('weight-unit/', include((patterns_weight_units, 'weight-unit'), namespace="weight-unit")),
]

wger/urls.py
# -*- coding: utf-8 -*-

# This file is part of wger Workout Manager.
#
# wger Workout Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# wger Workout Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Workout Manager.  If not, see <http://www.gnu.org/licenses/>.

# Django
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import (
    index,
    sitemap
)
from django.urls import path

# Third Party
from rest_framework import routers

# wger
from wger.core.api import views as core_api_views
from wger.exercises.api import views as exercises_api_views
from wger.exercises.sitemap import ExercisesSitemap
from wger.manager.api import views as manager_api_views
from wger.nutrition.api import views as nutrition_api_views
from wger.nutrition.sitemap import NutritionSitemap
from wger.utils.generic_views import TextTemplateView
from wger.weight.api import views as weight_api_views


#admin.autodiscover()


#
# REST API
#
router = routers.DefaultRouter()

#
# Application
#

# Manager app
router.register(r'day', manager_api_views.DayViewSet, basename='day')
router.register(r'set', manager_api_views.SetViewSet, basename='Set')
router.register(r'setting', manager_api_views.SettingViewSet, basename='Setting')
router.register(r'workout', manager_api_views.WorkoutViewSet, basename='workout')
router.register(r'workoutsession', manager_api_views.WorkoutSessionViewSet, basename='workoutsession')
router.register(r'workoutlog', manager_api_views.WorkoutLogViewSet, basename='workoutlog')
router.register(r'schedulestep', manager_api_views.ScheduleStepViewSet, basename='schedulestep')
router.register(r'schedule', manager_api_views.ScheduleViewSet, basename='schedule')

# Core app
router.register(r'daysofweek', core_api_views.DaysOfWeekViewSet, basename='daysofweek')
router.register(r'language', core_api_views.LanguageViewSet, basename='language')
router.register(r'license', core_api_views.LicenseViewSet, basename='license')
router.register(r'userprofile', core_api_views.UserProfileViewSet, basename='userprofile')
router.register(r'setting-repetitionunit', core_api_views.RepetitionUnitViewSet, basename='setting-repetition-unit')
router.register(r'setting-weightunit', core_api_views.WeightUnitViewSet, basename='setting-weight-unit')

# Exercises app
router.register(r'exerciseinfo', exercises_api_views.ExerciseInfoViewset, basename='exerciseinfo')
router.register(r'exercise', exercises_api_views.ExerciseViewSet, basename='exercise')
router.register(r'equipment', exercises_api_views.EquipmentViewSet, basename='api')
router.register(r'exercisecategory', exercises_api_views.ExerciseCategoryViewSet, basename='exercisecategory')
router.register(r'exerciseimage', exercises_api_views.ExerciseImageViewSet, basename='exerciseimage')
router.register(r'exercisecomment', exercises_api_views.ExerciseCommentViewSet, basename='exercisecomment')
router.register(r'muscle', exercises_api_views.MuscleViewSet, basename='muscle')

# Nutrition app
router.register(r'ingredient', nutrition_api_views.IngredientViewSet, basename='api-ingredient')
router.register(r'ingredientinfo', nutrition_api_views.IngredientInfoViewSet, basename='api-ingredientinfo')
router.register(r'weightunit', nutrition_api_views.WeightUnitViewSet, basename='weightunit')
router.register(r'ingredientweightunit', nutrition_api_views.IngredientWeightUnitViewSet, basename='ingredientweightunit')
router.register(r'nutritionplan', nutrition_api_views.NutritionPlanViewSet, basename='nutritionplan')
router.register(r'nutritionplaninfo', nutrition_api_views.NutritionPlanInfoViewSet, basename='nutritionplaninfo')
router.register(r'nutritiondiary', nutrition_api_views.LogItemViewSet, basename='nutritiondiary')
router.register(r'meal', nutrition_api_views.MealViewSet, basename='meal')
router.register(r'mealitem', nutrition_api_views.MealItemViewSet, basename='mealitem')

# Weight app
router.register(r'weightentry', weight_api_views.WeightEntryViewSet, basename='weightentry')

#
# Sitemaps
#
sitemaps = {'exercises': ExercisesSitemap,
            'nutrition': NutritionSitemap}

#
# The actual URLs
#
urlpatterns = i18n_patterns(
    #url(r'^admin/', admin.site.urls),
    path('', include(('wger.core.urls', 'core'), namespace='core')),
    path('workout/', include(('wger.manager.urls', 'manager'), namespace='manager')),
    path('exercise/', include(('wger.exercises.urls', 'exercise'), namespace='exercise')),
    path('weight/', include(('wger.weight.urls', 'weight'), namespace='weight')),
    path('nutrition/', include(('wger.nutrition.urls', 'nutrition'), namespace='nutrition')),
    path('software/', include(('wger.software.urls', 'software'), namespace='software')),
    path('config/', include(('wger.config.urls', 'config'), namespace='config')),
    path('gym/', include(('wger.gym.urls', 'gym'), namespace='gym')),
    path('email', include(('wger.mailer.urls', 'email'), namespace='email')),
    path('sitemap.xml', index, {'sitemaps': sitemaps}, name='sitemap'),
    path('sitemap-<section>.xml',
         sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
)

#
# URLs without language prefix
#
urlpatterns += [
    path('robots.txt',
         TextTemplateView.as_view(template_name="robots.txt"),
         name='robots'),

    # API
    path('api/v2/exercise/search/',
         exercises_api_views.search,
         name='exercise-search'),
    path('api/v2/exerciseinfo/search/',
         exercises_api_views.search,
         name='exercise-info'),
    path('api/v2/ingredient/search/',
         nutrition_api_views.search,
         name='ingredient-search'),
    path('api/v2/', include(router.urls)),

    # The api user login
    path('api/v2/login/', core_api_views.UserAPILoginView.as_view({
         'post': 'post'}), name='api_user'),
    path('api/v2/register/', core_api_views.UserAPIRegistrationViewSet.as_view({
         'post': 'post'}), name='api_register'),

    # Others
    path('api/v2/version/', core_api_views.ApplicationVersionView.as_view({
        'get': 'get'}), name='app_version'),

]

#
# URL for user uploaded files, served like this during development only
#
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wger/core/views/languages.py
# -*- coding: utf-8 -*-

# This file is part of wger Workout Manager.
#
# wger Workout Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# wger Workout Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License

# Standard Library
import logging

# Django
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin
)
from django.urls import reverse_lazy
from django.utils.translation import (
    gettext as _,
    gettext_lazy
)
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView
)

# wger
from wger.core.models import Language
from wger.utils.generic_views import (
    WgerDeleteMixin,
    WgerFormMixin
)


logger = logging.getLogger(__name__)


class LanguageListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    """
    Show an overview of all languages
    """
    model = Language
    template_name = 'language/overview.html'
    context_object_name = 'language_list'
    permission_required = 'core.change_language'


class LanguageDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Language
    template_name = 'language/view.html'
    context_object_name = 'view_language'
    permission_required = 'core.change_language'


class LanguageCreateView(WgerFormMixin, LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    """
    Generic view to add a new language
    """

    model = Language
    fields = ['short_name', 'full_name']
    title = gettext_lazy('Add')
    permission_required = 'core.add_language'


class LanguageDeleteView(WgerDeleteMixin, LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    """
    Generic view to delete an existing language
    """

    model = Language
    fields = ['short_name', 'full_name']
    success_url = reverse_lazy('core:language:overview')
    messages = gettext_lazy('Successfully deleted')
    permission_required = 'core.delete_language'

    def get_context_data(self, **kwargs):
        """
        Send some additional data to the template
        """
        context = super(LanguageDeleteView, self).get_context_data(**kwargs)
        context['title'] = _('Delete {0}?').format(self.object.full_name)
        return context


class LanguageEditView(WgerFormMixin, LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    """
    Generic view to update an existing language
    """

    model = Language
    fields = ['short_name', 'full_name']
    permission_required = 'core.change_language'

    def get_context_data(self, **kwargs):
        """
        Send some additional data to the template
        """
        context = super(LanguageEditView, self).get_context_data(**kwargs)
        context['title'] = _('Edit {0}').format(self.object.full_name)
        return context

wger/core/templates/user/api_key.html
{% extends "base.html" %}
{% load i18n static wger_extras %}

{% block title %}{% translate "API key" %}{% endblock %}


{% block content %}
{% with url='/api/v2/' %}
<p>{% blocktranslate %}Generate an API key if you want to interact with wger via
the <a href="{{url}}" rel="nofollow">REST API</a> it provides (for
public resources such as the exercises or ingredients, you don't need to provide
anything). You must pass this information in the header in the format shown below.{% endblocktranslate %}
{% endwith %}

<p>{% blocktranslate %}For security reasons, you should only access the API via HTTPS.{% endblocktranslate %}</p>
<div class="card mb-4 {% if token %}text-white bg-success{% else %}bg-light{% endif %}" >
    <div class="card-header">
        {% translate "Your API key" %}
    </div>
    <div class="card-body">
        {% if token %}
            <strong>{{token.key}}</strong>
        {% else %}
            <em>{% translate "You have no API key yet" %}</em>
        {% endif %}
    </div>
</div>

<h5>In the request header</h5>
<pre>
Authorization: Token {% if token %}{{token.key}}{% else %}1234567890abcde...{% endif %}
</pre>

<h5>Example with curl</h5>
<pre>
curl -X GET https://wger.de/api/v2/workout/ \
     -H 'Authorization: Token {% if token %}{{token.key}}{% else %}1234567890abcde...{% endif %}'
</pre>

{% endblock %}


{% block sidebar %}
<h4>{% translate "Options" %}</h4>

<p>
{% if token %}
    <a href="{% url 'core:user:api-key' %}?new_key=true" class="btn btn-block btn-light">{% translate 'Delete current API key and generate new one' %}</a>
{% else %}
    <a href="{% url 'core:user:api-key' %}?new_key=true" class="btn btn-block btn-light">{% translate 'Generate new API key' %}</a>
{% endif %}
</p>

<p>
    <a href="{% url 'software:api' %}" class="btn btn-block btn-light">{% translate 'Documentation' %}</a>
</p>
{% endblock %}

wger/core/templates/user/delete_account.html
{% extends "base.html" %}
{% load i18n static wger_extras crispy_forms_tags %}

{% block title %}{% translate "Delete account" %}{% endblock %}


{% block header %}
{% endblock %}

{% block content %}

<div class="wger-form">
    <div class="card bg-light">
        <div class="card-header">
            <h4 class="card-title">
                <span class="fa fa-exclamation-triangle" aria-hidden="true"></span>
                {% translate "Are you sure?" %}
            </h4>
        </div>
        <div class="card-body">
            {% with username=user_delete|format_username %}
            <p class="card-text">{% blocktranslate %}This action will delete the user account "{{username}}".
It will also  irrevocably remove all the data associated with it (workouts, logs, etc.)
and can't be undone. {% endblocktranslate %}{% endwith %}</p>
        </div>
    </div>
    <div class="mt-2"></div>
    {% crispy form %}
</div>
{% endblock %}


{% block sidebar %}
{% endblock %}

wger/core/templates/user/email_feedback.html
{% if user.is_authenticated %}
Feedback posted by {{user.username}} (ID: {{user.id}})
{% else %}
Feedback posted by an anonymous user
{% endif %}
------------------------------

Contact: {% if form_data.contact %}{{ form_data.contact }}{% else %}no contact{% endif %}
Message: {{ form_data.comment }}

wger/core/templates/user/list.html
{% extends "base.html" %}
{% load i18n static wger_extras django_bootstrap_breadcrumbs %}

{% block title %}{% translate "User list" %}{% endblock %}


{% block content %}
    {% include 'gym/partial_user_list.html' %}
{% endblock %}


{% block sidebar %}

{% endblock %}

wger/core/templates/user/login.html
{% extends "base.html" %}
{% load i18n static wger_extras crispy_forms_tags %}

{% block title %}{% translate "Login" %}{% endblock %}


{% block header %}
{% endblock %}

{% block content %}
    {% crispy form %}
{% endblock %}


{% block sidebar %}
<h4>{% translate "No account?" %}</h4>
<p>
    <a href="{% url 'core:user:registration' %}">
        <span class="{% fa_class 'sign-in-alt' %}"></span>
        {% translate "Register" %}
    </a>
</p>

<h4>{% translate "Forgot password?" %}</h4>
<p>
    <a href="{% url 'core:user:password_reset' %}" >
        <span class="{% fa_class 'key' %}"></span>
        {% translate "Reset password" %}
    </a>
</p>
{% endblock %}

wger/core/templates/user/preferences.html
{% extends "base.html" %}
{% load i18n static wger_extras crispy_forms_tags %}

{% block title %}{% translate "Preferences" %}{% endblock %}

{% block header %}
{% endblock %}


{% block content %}
    {% crispy form %}
{% endblock %}


{% block sidebar %}
{% endblock %}



{#         #}
{# Options #}
{#         #}
{% block options %}
<div class="btn-group">
    <div class="btn-group" role="group">
        <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="{% fa_class 'cog' %}"></span>
            {% translate "Options" %}
        </button>
        <div class="dropdown-menu">
            <a href="{% url 'core:user:change-password' %}" class="dropdown-item">
                <span class="{% fa_class 'key' %}"></span>
                {% translate "Change password" %}
            </a>
            <a href="{% url 'core:user:api-key' %}" class="dropdown-item">
                <span class="{% fa_class 'globe' %}"></span>
                {% translate "API key" %}
            </a>
            <div role="separator" class="dropdown-divider"></div>
            <a href="{% url 'core:user:delete' %}" class="wger-modal-dialog dropdown-item">
                <span class="{% fa_class 'trash' %}"></span>
                {% translate "Delete account" %}
            </a>
        </div>
    </div>
</div>
{% endblock %}